//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySAA
    {
        public int SAAID { get; set; }
        public int ResponseID { get; set; }
        public int QuestionID { get; set; }
        public string TextAnswer { get; set; }
        public System.TimeSpan TimeTaken { get; set; }
    
        public virtual SurveyQuestion SurveyQuestion { get; set; }
        public virtual SurveyResponse SurveyResponse { get; set; }
    }
}
